options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/docomo-jobs/docomo-event-actual-pipeline:$BUILD_ID
      - .

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/docomo-jobs/docomo-event-actual-pipeline:$BUILD_ID

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - docomo-event-actual-pipeline-prod
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/docomo-jobs/docomo-event-actual-pipeline:$BUILD_ID
      - --region
      - us-central1
      - --set-env-vars
      - PROJECT_ID=$PROJECT_ID,EVENT_ACTUAL_SHEET_ID=1bGboaI0sf5EFA5m0JerpDZBel6zz-N5Buo0Hql_pLdY,APP_ENV=production
